package dna

import "testing"

// func TestEncode(t *testing.T) {
// 	str := "Birney and Goldman"
// 	expectedDNA := "ATAGTATATCGACTAGTACAGCGTAGCATCTCGCAGCGAGATACGCTGCTACGCAGCATGCTGTGAGTATCGATGACGAGTGACTCTGTACAGTACGTACGATACGTACGTACGTCGTCATCTCGCAGCGAGATACGCTGCTACGCAGCATGCTGTGAGTATCGATGACGAGTGACTCTGTACAGTACGTACGTACGTACGTACGTACGTACGACTATATACGTACGTACGAGC"
// 	result := EncodeDNA(str)
// 	if result != expectedDNA {
// 		t.Errorf("Encode(%v))
// 	}
// }

func TestDecode(t *testing.T) {
	//input := "ATAGTATATCGACTAGTACAGCGTAGCATCTCGCAGCGAGATACGCTGCTACGCAGCATGCTGTGAGTATCGATGACGAGTGACTCTGTACAGTACGTACGATACGTACGTACGTCGTCATCTCGCAGCGAGATACGCTGCTACGCAGCATGCTGTGAGTATCGATGACGAGTGACTCTGTACAGTACGTACGTACGTACGTACGTACGTACGACTATATACGTACGTACGAGC"
	input := "ATAGTATATCGACTAGTACAGCGTAGCATCTCGCAGCGAGATACGCTGCTACGCAGCATGCTGTGAGTATCGATGACGAGTGACTCTGTACAGTACGTACGATACGTACGTACGTCGTCATCTCGCAGCGAGATACGCTGCTACGCAGCATGCTGTGAGTATCGATGACGAGTGACTCTGTACAGTACGTACGTACGTACGTACGTACGTACGACTATATACGTACGTACGAGC"
	expected := "Birney and Goldman"
	result := DecodeDNA(input)
	if result != expected {
		t.Errorf("Decoded failed, got:", result)
	}
}
