package dna

import (
	"testing"
)

func TestEncode(t *testing.T) {
	str := "Birney and Goldman"
	expectedDNA := "ATAGTATATCGACTAGTACAGCGTAGCATCTCGCAGCGAGATACGCTGCTACGCAGCATGCTGTGAGTATCGATGACGAGTGACTCTGTACAGTACGTACGATACGTACGTACGTCGTATAGTCGTACGTACGTACGTACGTACGTACGTACTGTACAGAGTCACTCGTCATCGATACTCACAGCATGCTGCGTAGCAGCGTATCTCGCTGCGAGATGATACGTACGTACGAGC"
	result := EncodeDNA(str)
	if result != expectedDNA {
		t.Errorf("Encoding failed, got:", result)
	}
}

func TestDecode(t *testing.T) {
	input := "ATAGTATATCGACTAGTACAGCGTAGCATCTCGCAGCGAGATACGCTGCTACGCAGCATGCTGTGAGTATCGATGACGAGTGACTCTGTACAGTACGTACGATACGTACGTACGTCGTATAGTCGTACGTACGTACGTACGTACGTACGTACTGTACAGAGTCACTCGTCATCGATACTCACAGCATGCTGCGTAGCAGCGTATCTCGCTGCGAGATGATACGTACGTACGAGC"
	expected := "Birney and Goldman"
	result := DecodeDNA(input)

	if result != expected {
		t.Errorf("Decoded failed, got:", result)
	}
}
